
```yaml
name: gacp_mobile
description: Mobile application for GACP Platform

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.12.0
  firebase_storage: ^12.5.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  syncfusion_flutter_charts: ^23.1.40
  syncfusion_flutter_maps: ^23.1.40
  image_picker: ^1.0.4
  tflite_flutter: ^0.9.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.1.11
  sensors_plus: ^1.3.0
  http: ^0.13.6
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 700